const VALUES_DATA = {
  environment: [
    "sustainability",
    "biodiversity",
    "solar",
    "pollutant",
    "organic",
    "pollution",
    "organism",
    "biology",
    "biological",
    "ecosystem",
    "microbe",
    "microorganism",
    "contaminant",
    "ecology",
    "environmentalist",
    "pesticide",
    "humidity",
    "forest",
    "deforestation",
    "outdoor",
    "conserve",
    "conservation",
    "sediment",
    "green",
    "contamination",
    "weather",
    "urbanization",
    "waste",
    "epa",
    "compost",
    "eco",
    "wastewater",
    "warming",
    "natural",
    "biological",
    "sensing",
    "species",
    "monitoring",
    "carbon",
    "degradation",
    "recycle",
    "chemical",
    "resource",
  ],
  small_business: [
    "small business",
    "independent",
    "women owned",
    "black owned",
    "bipoc",
    "craft",
    "hand made",
    "non-profit",
    "african american",
    "equality",
    "equity",
    "ethnic",
    "multicultural",
    "local",
    "one of a kind",
    "female owned",
    "artisan",
    "non profit",
    "alliance",
    "unique",
    "sustainable",
    "regional",
    "handmade",
    "native",
    "feminist",
    "equitable",
    "fair trade",
    "inclusive",
    "diverse",
    "accessible",
    "equal",
    "opportunity",
    "outreach",
    "public",
    "nonprofit",
    "good",
    "benefit",
    "support",
    "neighborhood",
    "area",
    "market",
    "brick and mortar",
    "shop small",
    "alliance",
    "marketplace",
    "union",
  ],
  privacy: [
    "privacy",
    "encryption",
    "secure",
    "security",
    "encrypted",
    "anonymous",
    "robust",
    "authentication",
    "vault",
    "protect",
    "authenticate",
    "private",
    "antivirus",
    "standards",
    "data",
    "password",
    "safeguard",
    "vulnerable",
    "biometric",
    "scanning",
    "breech",
    "warranty",
    "permission",
    "location",
    "hacker",
    "disclosure",
    "guarantee",
    "algorithm",
    "artificial intelligence",
    "blockchain",
    "connection",
    "crypto",
    "framework",
    "decentralize",
    "cybersecurity",
    "authority",
    "trusted",
    "certificate",
    "credential",
    "trust",
    "personal",
  ],
};
